export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Dashboard } from './Dashboard';
export { default as Files } from './Files';
export { default as Shares } from './Shares';
export { default as Trash } from './Trash';
export { default as Settings } from './Settings';
export { default as SharePage } from './SharePage';
export { default as Admin } from './Admin';
